# vim:ft=kitty

## name: cutiepro
## author: jezzy jumble
## license: GNU GPLv3
## upstream: A URL pointing to the location of this file upstream for auto-updates
## blurb: good theme


#: The basic colors

# chalk
foreground             #d5d0c9
# blackboard
background             #181716
# blackboard
selection_foreground   #181716
# chalk
selection_background   #d5d0c9


#: Cursor colors

# cherry_blossom
cursor              #e5a1a3
# sour_apple
cursor_text_color   #bed975
# cursor_trail_color  none


#: URL underline color when hovering with mouse

# salmon
url_color  #f58669


#: kitty window border colors and terminal bell colors

# active_border_color    #00ff00
# inactive_border_color  #cccccc
# bell_border_color      #ff5a00
# visual_bell_color      none


#: OS Window titlebar colors

# wayland_titlebar_color  system
# macos_titlebar_color    system


#: Tab bar colors

# active_tab_foreground    #000
# active_tab_background    #eee
# inactive_tab_foreground  #444
# inactive_tab_background  #999
# tab_bar_background       none
# tab_bar_margin_color     none


#: Colors for marks (marked text in the terminal)

# mark1_foreground  black
# mark1_background  #98d3cb
# mark2_foreground  black
# mark2_background  #f2dcd3
# mark3_foreground  black
# mark3_background  #f274bc


#: The basic 16 colors

#: black
# blackboard
color0   #181716
# elephant
color8   #88847f

#: red
# strawberry
color1   #f56e7f
# strawberry
color9   #f56e7f

#: green
# sour_apple
color2   #bec975
# sour_apple
color10  #bec975

#: yellow
# honeycomb
color3   #e8d6a7
# honeycomb
color11  #e8d6a7

#: blue
# lilac
color4   #c69ed1
# lilac
color12  #c69ed1

#: magenta
# cherry_blossom
color5   #e5a1a3
# cherry_blossom
color13  #e5a1a3

#: cyan
# sky
color6   #80c5de
# sky
color14  #80c5de

#: white
# chalk
color7   #d5d0c9
# chalk
color15  #d5d0c9
