# vim:ft=kitty
#: This is a template that can be used to create new kitty themes.
#: Theme files should start with a metadata block consisting of
#: lines beginning with ##. All metadata fields are optional.

## name: cutiepro
## author: jezzy jumble
## license: GNU GPLv3
## upstream: A URL pointing to the location of this file upstream for auto-updates
## blurb: good theme

#: All the settings below are colors, which you can choose to modify, or use the
#: defaults. You can also add non-color based settings if needed but note that
#: these will not work with using kitty @ set-colors with this theme. For a
#: reference on what these settings do see https://sw.kovidgoyal.net/kitty/conf/


#: The basic colors

foreground                      #d5d0c9
background                      #181716
selection_foreground            #181716
selection_background            #d5d0c9


#: Cursor colors

cursor                          #e5a1a3
cursor_text_color               #bed975
# cursor_trail_color              none


#: URL underline color when hovering with mouse

url_color                       #f58669


#: kitty window border colors and terminal bell colors

# active_border_color             #00ff00
# inactive_border_color           #cccccc
# bell_border_color               #ff5a00
# visual_bell_color               none


#: OS Window titlebar colors

# wayland_titlebar_color          system
# macos_titlebar_color            system


#: Tab bar colors

# active_tab_foreground           #000
# active_tab_background           #eee
# inactive_tab_foreground         #444
# inactive_tab_background         #999
# tab_bar_background              none
# tab_bar_margin_color            none


#: Colors for marks (marked text in the terminal)

# mark1_foreground                black
# mark1_background                #98d3cb
# mark2_foreground                black
# mark2_background                #f2dcd3
# mark3_foreground                black
# mark3_background                #f274bc


#: The basic 16 colors

#: black
color0                          #181716
color8                          #88847f

#: red
color1                          #f56e7f
color9                          #f56e7f

#: green
color2                          #bec975
color10                         #bec975

#: yellow
color3                          #e8d6a7
color11                         #e8d6a7

#: blue
color4                          #c69ed1
color12                         #c69ed1

#: magenta
color5                          #e5a1a3
color13                         #e5a1a3

#: cyan
color6                          #80c5de
color14                         #80c5de

#: white
color7                          #d5d0c9
color15                         #d5d0c9


#: You can set the remaining 240 colors as color16 to color255.
