"attribute" = "creamsicle"

"type" = "creamsicle"
# "type.builtin"
# "type.enum"
# "type.enum.variant" = "cherry_blossom"

"constructor" = "lilac"

"constant" = "sky"
# "constant.builtin"
# "constant.builtin.boolean"
# "constant.character" = "cherry_blossom"
# "constant.character.escape" = "sky"
# "constant.numeric"
# "constant.numeric.integer"
# "constant.numeric.float"

"string" = "sour_apple"
"string.regexp" = "lilac"
"string.special" = "indigo"
"string.special.path" = "cyan"
"string.special.url" = { fg = "cyan", underline.style = "line" }
"string.special.symbol" = "indigo"

"comment" = "elephant"
# "comment.line"
# "comment.line.documentation"
# "comment.block"
# "comment.block.documentation"
# "comment.unused"

"variable" = "cherry_blossom"
# "variable.builtin"
# "variable.parameter"
# "variable.other"
# "variable.other.member"
# "variable.other.member.private"

"label" = "green"

"punctuation" = "honeycomb"
# "punctuation.delimiter"
# "punctuation.bracket"
"punctuation.special" = "strawberry"

"keyword" = "strawberry"
# "keyword.control"
# "keyword.control.conditional"
# "keyword.control.repeat"
# "keyword.control.import"
# "keyword.control.return"
# "keyword.control.exception"
# "keyword.operator"
# "keyword.directive"
# "keyword.function"
# "keyword.storage"
# "keyword.storage.type"
# "keyword.storage.modifier"

"operator" = "honeycomb"

"function" = "lilac"
# "function.builtin"
# "function.method"
# "function.method.private"
# "function.macro"
# "function.special"

"tag" = "salmon"
# "tag.builtin"

"namespace" = "salmon"

"special" = "pink"

# "markup"
# "markup.normal"
# "markup.normal.completion"
# "markup.normal.hover"
"markup.heading" = { fg = "cherry_blossom", underline = { color = "cherry_blossom", style = "dashed" } }
# "markup.heading.marker"
# "markup.heading.1"
# "markup.heading.2"
# "markup.heading.3"
# "markup.heading.4"
# "markup.heading.5"
# "markup.heading.6"
# "markup.heading.completion"
# "markup.heading.hover"
"markup.list" = "sky"
# "markup.list.unnumbered"
# "markup.list.numbered"
# "markup.list.checked"
# "markup.list.unchecked"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
# "markup.link"
"markup.link.url" = { fg = "cyan", underline.style = "line" }
"markup.link.label" = "cyan"
"markup.link.text" = "lilac"
"markup.quote" = "elephant"
"markup.raw" = "sour_apple"
# "markup.raw.inline"
# "markup.raw.inline.completion"
# "markup.raw.inline.hover"
# "markup.raw.block"

# "diff"
"diff.plus" = "sour_apple"
# "diff.plus.gutter"
"diff.minus" = "strawberry"
# "diff.minus.gutter"
"diff.delta" = "sky"
"diff.delta.moved" = "creamsicle"
"diff.delta.conflict" = "lilac"
# "diff.delta.gutter"

"ui.background" = { bg = "blackboard" }
"ui.background.separator" = "cherry_blossom"

"ui.cursor" = { bg = "chalk", fg = "blackboard" }
# "ui.cursor.normal"
# "ui.cursor.insert"
# "ui.cursor.select"
"ui.cursor.match" = { fg = "lemon", modifiers = ["bold"], underline.style = "line" }
"ui.cursor.primary" = { fg = "blackboard" }
"ui.cursor.primary.normal" = { bg = "cherry_blossom", fg = "blackboard" }
"ui.cursor.primary.insert" = { bg = "sour_apple", fg = "blackboard" }
"ui.cursor.primary.select" = { bg = "sky", fg = "blackboard" }

"ui.debug.breakpoint" = "pink"
"ui.debug.active" = "pink"

# "ui.gutter"
# "ui.gutter.selected"

"ui.linenr" = "elephant"
"ui.linenr.selected" = { fg = "cherry_blossom", modifiers = ["bold"] }

"ui.statusline" = { bg = "noir", fg = "chalk" }
"ui.statusline.inactive" = { modifiers = ["dim"] }
"ui.statusline.normal" = { bg = "cherry_blossom", fg = "blackboard" }
"ui.statusline.insert" = { bg = "sour_apple", fg = "blackboard" }
"ui.statusline.select" = { bg = "sky", fg = "blackboard" }
"ui.statusline.separator" = { modifiers = ["bold"] }

"ui.bufferline" = { fg = "elephant" }
"ui.bufferline.active" = { fg = "cherry_blossom", underline.style = "line" }
"ui.bufferline.background" = { bg = "blackboard" }

"ui.popup" = { bg = "noir" }
"ui.popup.info" = { bg = "noir", fg = "creamsicle" }

# "ui.picker.header"
# "ui.picker.header.column"
"ui.picker.header.column.active" = { modifiers = ["bold"], underline = { color = "cherry_blossom", style = "line" } }

"ui.window" = "cherry_blossom"

"ui.help" = { fg = "honeycomb", bg = "noir" }

"ui.text" = "chalk"
"ui.text.focus" = { bg = "metal" }
"ui.text.inactive" = { fg = "elephant" }
"ui.text.info" = "honeycomb"
# "ui.text.directory" = "creamsicle"
"ui.text.directory" = "creamsicle"

"ui.virtual.ruler" = "elephant"
"ui.virtual.whitespace" = "elephant"
"ui.virtual.indent-guide" = "noir"
"ui.virtual.inlay-hint" = { fg = "gray", modifiers = ["italic"] }
# "ui.virtual.inlay-hint.parameter"
# "ui.virtual.inlay-hint.type"
"ui.virtual.wrap" = "elephant"
"ui.virtual.jump-label" = { fg = "lemon", modifiers = ["bold", "italic"] }

# FIXME
"ui.menu" = { bg = "noir" }
"ui.menu.selected" = { fg = "cherry_blossom", modifiers = ["bold"], underline = { color = "cherry_blossom", style = "line" } }
"ui.menu.scroll" = { bg = "noir", fg = "cherry_blossom" }

"ui.selection" = { bg = "liquorice" }
"ui.selection.primary" = { bg = "ocean" }

"ui.highlight" = { bg = "metal" }
# "ui.highlight.frameline"

"ui.cursorline.primary" = { bg = "metal" }
# "ui.cursorline.secondary"

"ui.cursorcolumn.primary" = { bg = "metal" }
# "ui.cursorcolumn.secondary"

"warning" = { bg = "noir", fg = "creamsicle" }
"error" = { bg = "noir", fg = "strawberry" }
"info" = { bg = "noir", fg = "lilac" }
"hint" = { bg = "noir", fg = "chalk" }

"diagnostic" = { underline = { color = "chalk", style = "curl" } }
"diagnostic.hint" = { underline = { color = "chalk", style = "curl" } }
"diagnostic.info" = { underline = { color = "lilac", style = "curl" } }
"diagnostic.warning" = { underline = { color = "creamsicle", style = "curl" } }
"diagnostic.error" = { underline = { color = "strawberry", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

# "tabstop" = { modifiers = ["italic"] }

[palette]
# shades of gray and supporting colors
blackboard = "#181716"
metal = "#242628"
noir = "#2e2a27"
liquorice = "#383838"
ocean = "#0f3f4e"
elephant = "#88847f"
chalk = "#d3ccba"
lemon = "#ffef43"

# accent colors
strawberry = "#f56e7f"
cherry_blossom = "#e5a1a3"
lilac = "#bc96c7"
sky = "#92bbc9"
sour_apple = "#bec975"
honeycomb = "#dfcfa3"
creamsicle = "#f3b061"
salmon = "#f58669"

pink = "#ed83bb"
indigo = "#9c9de4"
cyan = "#7cbda1"
# green = "#78dd6c"
green = "#7ac973"
gray = "#73665b"
