fish_color_autosuggestion 73665b
fish_color_cancel f56e7f
fish_color_command bea2c6
fish_color_comment 88847f
fish_color_cwd e8d6a7
fish_color_cwd_root f3b061
fish_color_end e8d6a7
fish_color_escape 9697e4
fish_color_error f58669
fish_color_history_current e5a1a3 --bold --underline
fish_color_host d5d0c9
fish_color_host_remote 9697e4
fish_color_keyword f56e7f
fish_color_normal d5d0c9
fish_color_operator e8d6a7
fish_color_option f3b061
fish_color_param e5a1a3
fish_color_quote bec975
fish_color_redirection ed83bb
fish_color_search_match '--background=0f3f4e' --bold --italics
fish_color_selection '--background=0f3f4e'
fish_color_status f56e7f
fish_color_user e5a1a3 --bold
fish_color_valid_path 92bbc9
fish_pager_color_completion d5d0c9
fish_pager_color_description e8d6a7 --italics
fish_pager_color_prefix f3b061
fish_pager_color_progress 181716 '--background=e5a1a3'
fish_pager_color_selected_background '--background=242628'
fish_pager_color_selected_completion e5a1a3 --bold --underline
fish_pager_color_selected_description e8d6a7 --italics --underline
